### ISSUE TITLE
Support for setting SSE

### ISSUE THREAD

**Issue by PhilKershaw** [serverless-components/aws-dynamodb#13]
This is 1 of 2 features I believe would open this component up to wider use, particularly in shared AWS accounts. Is anyone currently working on adding this - before I give it a shot mysaelf?

**Comment by PhilKershaw** [comment]
Looks like master is both broken and undergoing a massive transistion. I'll leave the issue open but will hold off and contributing for the time being.

**Comment by eahefnawy** [comment]
@PhilKershaw we're done migrating this component to V2. It should be stable now.
