### ISSUE TITLE
Prefix resourceId with a name for the table name

### ISSUE THREAD

**Issue by dodgeblaster** [serverless-components/aws-dynamodb#3]
Having the table name generated makes sense to avoid errors and collisions but it might make it hard to find and work with dynamo tables in the aws console. What about prefixing the resourceId name with a string from the inputs:

```js
class AwsDynamoDb extends Component {
  async default(inputs = {}) {
    this.context.status('Deploying')
    const config = mergeDeepRight(defaults, inputs)

    const generatedName = inputs.name + this.context.resourceId()
    config.name = this.state.name || generatedName

```

**Comment by eahefnawy** [comment]
Thanks for suggesting that @dodgeblaster ... we get that a lot actually and I think you're right. I think it's best to just offer an **optional** name input. Should be super easy. PR welcome!
